exercise1:
	clang++ -std=c++17 exercise1.cpp && ./a.out

exercise2:
	clang++ -std=c++17 exercise2.cpp && ./a.out

exercise3:
	clang++ -std=c++17 exercise3.cpp && ./a.out

exercise4:
	clang++ -std=c++17 exercise4.cpp && ./a.out

exercise6:
	clang++ -std=c++17 exercise6.cpp && ./a.out

exercise7:
	clang++ -std=c++17 exercise7.cpp && ./a.out